config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   resources :users, only: [:index, :show] do
     resources :posts, only: [:index, :new, :create, :show, :destroy] do
       resources :comments, only: [:new, :create, :destroy]
       resources :likes, only: [:create]
     end
   end
 
   # api routes
   namespace :api do
     resources :users, only: [:index, :show] do
       resources :posts, only: [:index], format: :json do
         resources :comments, only: [:index, :create], format: :json
       end
     end
   end
 
   root "users#index"
 end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def last_three_posts
    posts.where(author_id: self).order('created_at DESC').limit(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<main>
  <section class="users-list">
    <h2>List of users</h2>
    <% if @users.empty? %>
      <h3>Currently there are not users in the database</h3>
    <% else %>
      <% @users.each do |user| %>
        <div class="users-section">
          <%= link_to user_path(user.id) do %>
            <div class="user-card">
              <div class="image-container">
                <img src="<%=user.photo || image_url('user_icon.png') %>" alt="Image of user <%=user.name %>" title="<%=user.name %>" class="user-image">
              </div>
              <div class="name-counter"
                <h4><%= user.name %></h4>
                <p>Number of posts: <%= user.post_counter %></p>
              </div>
            </div>
          <% end %>
          
        </div>
      <% end %>
    <% end %>
  </section>
</main>

app/views/users/show.html.erb
<main>
  <section class="users-section">
    <h2>User information</h2>
    <article class="users-info">
      <div class="user-card">
        <div class="image-container">
          <img src="<%=@user.photo || image_url('user_icon.png') %>" alt="Image of user <%=@user.name %>" title="<%=@user.name %>" class="user-image">
        </div>
        <div class="name-counter"
          <h4><%= @user.name %></h4>
          <p>Number of posts: <%= @user.post_counter %></p>
        </div>
      </div>
    </article>

    <article class="users-bio">
      <p>User bio:  <%= @user.bio %></p>
    </article>

    <article class="users-posts">
      <% if @user.last_three_posts.empty? %>
        <h3>Currently there are not posts in the database for this user</h3>
      <% else %>
        <% @user.last_three_posts.each do |post| %>
          <div class="posts-section">
            <%= link_to user_post_path(@user.id, post.id) do %>
              <div class="posts-card"> 
                <h4>Post #: <%= post.id %> - <%= post.title %></h4>
            <% end %>
                <p class="post-text"><%= post.text %></p>
                <p class="post-comments-likes">
                  Comments: <%= post.comments_counter %> - Likes: <%= post.likes_counter %>
                </p>
              </div>
            
            
          </div>
        <% end %>
      <% end %>
    </article>

    <%= link_to new_user_post_path(@user) do %>
      <button class="see-all-button">Create a new post</button>
    <% end %>
    <%= link_to user_posts_path(@user) do %>
      <button class="see-all-button">See all posts</button>
    <% end %>
    
    <%= link_to users_path do %>
      <button class="see-all-button">Back to users list</button>
    <% end %>
    

  </section>
</main>