config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   resources :users, only: [:index, :show] do
     resources :posts, only: [:index, :new, :create, :show, :destroy] do
       resources :comments, only: [:new, :create, :destroy]
       resources :likes, only: [:create]
     end
   end
 
   # api routes
   namespace :api do
     resources :users, only: [:index, :show] do
       resources :posts, only: [:index], format: :json do
         resources :comments, only: [:index, :create], format: :json
       end
     end
   end
 
   root "users#index"
 end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  def recent_five_comments
    Comment.includes(:author).where(post_id: self).order('created_at DESC').limit(5)
  end

  private

  def update_post_counter
    author.increment!(:post_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authenticate_user!
  respond_to :json

  def index
    @posts = current_user.posts
    render json: { posts: @posts }, status: :ok
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  # load_and_authorize_resource

  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = @user.posts

    respond_to do |format|
      format.html
      format.json { render json: @posts }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = Comment.where(posts_id: params[:id])
    # @comments = Comment.where(post_id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(strong_params)

    if @post.save
      flash[:success] = 'Post saved!'
      redirect_to user_path(current_user.id)
    else
      flash.now[:error] = 'Please fill all fields'
      render :new, status: 422
    end
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to user_path(current_user)
    flash[:success] = 'The post was successfully destroyed.'
  end

  rescue_from CanCan::AccessDenied do
    redirect_to '/sign_in'
  end

  private

  def strong_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<main>
  <section class="posts-section">
    <h2>Posts information for user</h2>
    <article class="users-info">
      <div class="user-card">
        <div class="image-container">
          <img src="<%=@user.photo || image_url('user_icon.png') %>" alt="Image of user <%=@user.name %>" title="<%=@user.name %>" class="user-image">
        </div>
        <div class="name-counter"
          <h3><%= @user.name %></h3>
          <p>Number of posts: <%= @user.post_counter %></p>
        </div>
      </div>
    </article>

    <article class="users-posts">
      <% if @posts.empty? %>
        <h3>Currently there are not posts in the database for this user</h3>
      <% else %>
        <% @posts.each do |post| %>
          <div class="posts-section">
            <div class="posts-card">
              
            <a href='posts/<%=post.id%>'><h4>Post #: <%= post.id %> - <%= post.title %></a></h4>
        <p class="post-text" maxlength= 150><%= post.text %></p>
        <p class="post-comments-likes">

        <% if can? :manage, post %>
          <%= button_to 'Delete post', user_post_path(@user, post.id), method: :delete, class: 'delete-btn' %>
        <% end %>

        <a href='posts/<%=post.id%>'>See more</a>
        </p>
            </div>
          </div>


        Comments: <%= post.comments_counter %> - Likes: <%= post.likes_counter %>
      </p>

    

    
            
            
            </div>
            <ul class="five-comments">
              <% post.recent_five_comments.each do |comment| %>
                <li class="comment"><%= comment.author.name %>: <%= comment.text %></li>
              <% end %>
            </ul>
          </div>
          
       <% end %>
     <% end %>
    </article>

    <button>
      Pagination
    </button>
    
    <%= link_to user_path(@user) do %>
      <button class="see-all-button">Back to user's short list</button>
    <% end %>
    
  </section>
</main>

app/views/posts/new.html.erb
<div class="new-post-form">

  <h1>Create a new post</h1>

</div>

<%= form_with model: Post, url: user_posts_path , class: 'post-form', method: :post do |f| %>

  <div class="newpost-title">

    <%= f.label :title, 'Post title: ' %>
    <%= f.text_field :title, placeholder: 'Write the title of your post here', :required => true, class: 'new-title' %>

  </div>

  <div class="newpost-text">

    <%= f.label :text, 'Post content:' %>
    <%= f.text_area :text, placeholder: 'Write your post here', :required => true, class: 'new-text' %>

  </div>

  <%= f.submit "Submit", class: 'submit-post' %>
<% end %>

app/views/posts/show.html.erb
<main>
  <section class="post-section">
    <h2>Information for post</h2>
    <article class="post-info">
      <div class="post-card">
        <h3><%= @post.title %> by user:  <%= @user.name %></h3>
        <p>Number of comments: <%= @post.comments_counter %> - Number of likes: <%= @post.likes_counter %></p>
        <p class="post-text"><%= @post.text %></p>
      </div>
    </article>

    <article class="comments">

        <ul class="total-comments">
          <% @post.comments.includes(:author).each do |comment| %>
            <li class="comment"><%= comment.author.name %>: <%= comment.text %>

         <% if can? :manage, comment %>
                <%= button_to 'Delete comment', user_post_comment_path(@user, @post, comment), method: :delete, class: 'delete-btn' %>
              <% end %>

</li>
        
          <% end %>
        </ul>
      
    </article>
    
    <h3>Make a new comment on this post</h3>

    <%= form_with url: user_post_comments_url(@user, @post), method: :post, local: true, scope: :comment do |f| %>

      <div class="comment-area">
        <%= f.label :text, "Enter your comment here:" %><br>
        <%= f.text_area :text, class: 'text-area' %>
      </div>

      <%= f.submit "Create comment", class: 'submit-comment' %>
    <% end %>


    <h3>Give a like to this post</h3>

    <%= form_with model: Like, url: user_post_likes_url(@user, @post) , class: 'like-form', method: :post do |f| %>
      <%= f.submit "Give like" %>
    <% end %>
    
    <%= link_to user_posts_path(@user) do %>
      <button class="see-all-button">Back to list of posts</button>
    <% end %>

  </section>
</main>